"""rename email to email_primary and add colunm email in user profile

Revision ID: 0d42a4688d89
Revises: e23879915f67
Create Date: 2025-01-18 15:07:40.591859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d42a4688d89'
down_revision: Union[str, None] = 'e23879915f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserProfile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_secondary', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_profile')
    op.add_column('user_account', sa.Column('email_primary', sa.String(length=255), nullable=False))
    op.drop_index('ix_user_account_email', table_name='user_account')
    op.create_index(op.f('ix_user_account_email_primary'), 'user_account', ['email_primary'], unique=True)
    op.drop_column('user_account', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_account_email_primary'), table_name='user_account')
    op.create_index('ix_user_account_email', 'user_account', ['email'], unique=True)
    op.drop_column('user_account', 'email_primary')
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name='user_profile_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_profile_pkey')
    )
    op.drop_table('UserProfile')
    # ### end Alembic commands ###
