"""adjust rubber farm

Revision ID: 0e8bf6da4832
Revises: 7c4f48968e69
Create Date: 2025-03-05 16:16:41.544631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8bf6da4832'
down_revision: Union[str, None] = '7c4f48968e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Permission', sa.Column('url_action', sa.String(length=255), nullable=False))
    op.drop_column('Permission', 'url_acion')
    op.add_column('RolePermission', sa.Column('permission_id', sa.Integer(), nullable=False))
    op.drop_constraint('role_module_uc', 'RolePermission', type_='unique')
    op.create_unique_constraint('role_module_permission_uc', 'RolePermission', ['role_id', 'module_id', 'permission_id'])
    op.create_foreign_key(None, 'RolePermission', 'Permission', ['permission_id'], ['id'], ondelete='CASCADE')
    op.add_column('RubberFarm', sa.Column('document_type', sa.String(length=100), nullable=True))
    op.add_column('RubberFarm', sa.Column('citzen_id', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'UserRole', type_='unique')
    op.drop_column('RubberFarm', 'citzen_id')
    op.drop_column('RubberFarm', 'document_type')
    op.drop_constraint(None, 'RolePermission', type_='foreignkey')
    op.drop_constraint('role_module_permission_uc', 'RolePermission', type_='unique')
    op.create_unique_constraint('role_module_uc', 'RolePermission', ['role_id', 'module_id'])
    op.drop_column('RolePermission', 'permission_id')
    op.add_column('Permission', sa.Column('url_acion', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('Permission', 'url_action')
    # ### end Alembic commands ###
