"""adjust rubbertype table

Revision ID: 34898a5cf14a
Revises: cb08b0a7d01e
Create Date: 2025-03-05 19:22:06.776400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34898a5cf14a'
down_revision: Union[str, None] = 'cb08b0a7d01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('RubberFarm', 'citizen_id',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=14),
               existing_nullable=True)
    op.add_column('RubberType', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('RubberType', 'name_en')
    op.drop_column('RubberType', 'name_th')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'UserRole', type_='unique')
    op.add_column('RubberType', sa.Column('name_th', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('RubberType', sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('RubberType', 'name')
    op.alter_column('RubberFarm', 'citizen_id',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True)
    # ### end Alembic commands ###
