"""adjust soilgeo type of ft float to string 2

Revision ID: 3604581f4468
Revises: 7a8b72147b0f
Create Date: 2025-03-05 19:38:35.753804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3604581f4468'
down_revision: Union[str, None] = '7a8b72147b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SoilGeography', 'ph_top',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('SoilGeography', 'ph_low',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'UserRole', type_='unique')
    op.alter_column('SoilGeography', 'ph_low',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('SoilGeography', 'ph_top',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
