"""update 3

Revision ID: 5b53c9f840b3
Revises: 
Create Date: 2025-01-20 17:34:52.866436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b53c9f840b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Geography',
    sa.Column('code', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_th', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_th')
    )
    op.create_table('NumberTest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('api_endpoint', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('RubberType',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SoilType',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserAccount',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_primary', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_UserAccount_email_primary'), 'UserAccount', ['email_primary'], unique=True)
    op.create_table('casbin_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sa.String(length=255), nullable=True),
    sa.Column('v0', sa.String(length=255), nullable=True),
    sa.Column('v1', sa.String(length=255), nullable=True),
    sa.Column('v2', sa.String(length=255), nullable=True),
    sa.Column('v3', sa.String(length=255), nullable=True),
    sa.Column('v4', sa.String(length=255), nullable=True),
    sa.Column('v5', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Province',
    sa.Column('code', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_th', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('geography_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['geography_id'], ['Geography.code'], ),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_th')
    )
    op.create_table('RolePermission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['Permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('UserProfile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_secondary', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['UserAccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserRole',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['UserAccount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('District',
    sa.Column('code', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_th', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['Province.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('WeatherGeography',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('average_temperature', sa.Float(), nullable=True),
    sa.Column('average_humidity', sa.Float(), nullable=True),
    sa.Column('rainy_day_count', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['Province.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SubDistrict',
    sa.Column('code', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_th', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['District.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('SoilGeography',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subdistrict_id', sa.Integer(), nullable=False),
    sa.Column('soil_type_id', sa.Integer(), nullable=False),
    sa.Column('fertility_top', sa.Float(), nullable=True),
    sa.Column('ph_top', sa.Float(), nullable=True),
    sa.Column('ph_low', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['soil_type_id'], ['SoilType.id'], ),
    sa.ForeignKeyConstraint(['subdistrict_id'], ['SubDistrict.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RubberFarm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('soil_id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('subdistrict_id', sa.Integer(), nullable=False),
    sa.Column('rubber_type_id', sa.Integer(), nullable=False),
    sa.Column('rubber_area', sa.Float(), nullable=True),
    sa.Column('rubber_tree_count', sa.Integer(), nullable=True),
    sa.Column('rubber_tree_age', sa.Integer(), nullable=True),
    sa.Column('dry_rubber_content', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rubber_type_id'], ['RubberType.id'], ),
    sa.ForeignKeyConstraint(['soil_id'], ['SoilGeography.id'], ),
    sa.ForeignKeyConstraint(['subdistrict_id'], ['SubDistrict.code'], ),
    sa.ForeignKeyConstraint(['weather_id'], ['WeatherGeography.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RubberFarm')
    op.drop_table('SoilGeography')
    op.drop_table('SubDistrict')
    op.drop_table('WeatherGeography')
    op.drop_table('District')
    op.drop_table('UserRole')
    op.drop_table('UserProfile')
    op.drop_table('RolePermission')
    op.drop_table('Province')
    op.drop_table('casbin_rule')
    op.drop_index(op.f('ix_UserAccount_email_primary'), table_name='UserAccount')
    op.drop_table('UserAccount')
    op.drop_table('SoilType')
    op.drop_table('RubberType')
    op.drop_table('Role')
    op.drop_table('Permission')
    op.drop_table('NumberTest')
    op.drop_table('Geography')
    # ### end Alembic commands ###
