"""add new table module

Revision ID: 7c4f48968e69
Revises: 5db4fb197e43
Create Date: 2025-02-27 06:26:17.891001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4f48968e69'
down_revision: Union[str, None] = '5db4fb197e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Module',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('Permission', sa.Column('url_acion', sa.String(length=255), nullable=False))
    op.add_column('Permission', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('Permission', sa.Column('module_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Permission', 'Module', ['module_id'], ['id'])
    op.drop_column('Permission', 'api_endpoint')
    op.add_column('RolePermission', sa.Column('module_id', sa.Integer(), nullable=False))
    op.add_column('RolePermission', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint('role_module_uc', 'RolePermission', ['role_id', 'module_id'])
    op.drop_constraint('RolePermission_permission_id_fkey', 'RolePermission', type_='foreignkey')
    op.create_foreign_key(None, 'RolePermission', 'Module', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_column('RolePermission', 'permission_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'UserRole', type_='unique')
    op.add_column('RolePermission', sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'RolePermission', type_='foreignkey')
    op.create_foreign_key('RolePermission_permission_id_fkey', 'RolePermission', 'Permission', ['permission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('role_module_uc', 'RolePermission', type_='unique')
    op.drop_column('RolePermission', 'is_active')
    op.drop_column('RolePermission', 'module_id')
    op.add_column('Permission', sa.Column('api_endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Permission', type_='foreignkey')
    op.drop_column('Permission', 'module_id')
    op.drop_column('Permission', 'is_active')
    op.drop_column('Permission', 'url_acion')
    op.drop_table('Module')
    # ### end Alembic commands ###
