"""Add foreign key relationship between UserAccount and UserProfile

Revision ID: 83475ea4d287
Revises: 78fceca02969
Create Date: 2024-12-30 09:41:54.030088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83475ea4d287'
down_revision: Union[str, None] = '78fceca02969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_profile', 'user_account', ['user_id'], ['id'])
    op.drop_column('user_profile', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_column('user_profile', 'user_id')
    # ### end Alembic commands ###
